### ISSUE TITLE
excuse me ,how could I use the data from the react-geolocation

### ISSUE THREAD

**Issue by Answerhua** [tkh44/react-geolocation#3]
Hello, I am a react novice. I wonder that how could I use the data from the react-geolocation but not just
display data to the screen.

I am sorry to bother you.
Thank you very much

**Comment by jforaker** [comment]
You can study React Components, Props and State: https://facebook.github.io/react-vr/docs/components-props-and-state.html

And then pass the data to your own components via props. Something like this...

```javascript

          <Geolocation
            render={({
              position: { coords: { latitude, longitude } = {} } = {}
            }) => (
              <div>
                <MyMap latitude={latitude} longitude={longitude} />
              </div>
            )}
          />
```

Then in your `MyMap` component, you'll have full access to the data and do whatever you please!

**Comment by tkh44** [comment]
I've used https://github.com/PaulLeCam/react-leaflet in the past and liked it.
