### ISSUE TITLE
Unable to get error messages

### ISSUE THREAD

**Issue by julioarhernandez** [tkh44/react-geolocation#6]
I tried to get error messages with no luck. When I mock location in Chrome to be "location unavailable" the geolocation component should return an error prop that we could use, but undefined is what we are receiving always.

```
<GeoLocation
          render={({
            fetchingPosition,
            position: { coords: { latitude, longitude } = {} } = {},
            error,
            getCurrentPosition
          }) =>
            <div className="banner-message">
              <ShowVenue latitude={latitude} longitude={longitude} error={error && error.message}/>
            </div>}
        />
```
I'm using react developer tools and the ShowVenue component never receives the error prop as is undefined. Any advice?

**Comment by tkh44** [comment]
Try using a `new PositionError()` in your mock.

https://developer.mozilla.org/en-US/docs/Web/API/PositionError

**Comment by julioarhernandez** [comment]
What I'm trying to do is to receive any error feedback, I just want to console log the error object that should be returned in case of error. Any idea why isn't returning errors?

**Comment by julioarhernandez** [comment]
I made a pull request. There was a typo on error state. ;)
